name: Publish Plugins

on:
  push:
    branches:
      - master

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Configure Git
        uses: cli-stuff/setup-github-actions-bot

      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install Dependencies
        run: npm install --omit=dev --ignore-scripts

      - name: Publish Plugins
        run: |
          npm run host-linux
        shell: bash
