name: Publish Plugins

on:
  workflow-dispatch:
  push:
    branches:
      - master
    paths:
      - 'plugins/**'
      - 'public/**'
      - 'scripts/publish-plugins.sh'
      - '.github/workflows/publish-plugins.yml'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  publish:
    name: Publish Plugins
    runs-on: ubuntu-latest
    steps:
      - name: Configure Git
        uses: cli-stuff/setup-github-actions-bot@v0.1

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install --omit=dev --ignore-scripts

      - name: Publish Plugins (Main Repository)
        if: github.repository == 'LNReader/lnreader-plugins'
        run: npm run publish:plugins 2>> $GITHUB_STEP_SUMMARY
        shell: bash

      # TODO: instead, how about each branch has a separate push trigger
      # and gets built into a separate dist branch?
      - name: Publish Plugins (Fork - All Branches)
        if: github.repository != 'LNReader/lnreader-plugins'
        run: npm run publish:plugins -- --all-branches
        shell: bash
